Matterbot:
  host: "<your-mattermost-host>"
  port: 443
  scheme: "https"
  basepath: "/api/v4"
  username: "<mattermost bot account name>"
  password: "<mattermost bot password>"
  teamname: "<mattermost team identifier>"
  botadmins: # Can be either a Mattermost userid or role name (e.g. 'system_admin')
    - "<your-mattermost-id-here>"
    - "system_admin"
  logfile: "matterfeed.log"
  bindmap: "bindmap.json"
  feedmap: "feedmap.json"
  helpcmds: # Do not change these, or things might break
    - "!help"
    - "@help"
  mapcmds: # Do not change these, or things might break
    - "!bind"
    - "@bind"
    - "!unbind"
    - "@unbind"
    - "!map"
    - "@map"
  feedmode: "admin" # "admin" means only admins can use the feedcmds. Change to "user" for user-level access.
                    # Be careful: in "user" mode, users may be able to subscribe to sensitive feed modules,
                    # unless the feed's own settings restrict it to admin mode! Check the modules directory
                    # for examples on how to do this.
  feedcmds: # Do not change these, or things might break
    - "!subscribe"
    - "!sub"
    - "@subscribe"
    - "@sub"
    - "!unsubscribe"
    - "!unsub"
    - "@unsubscribe"
    - "@unsub"
    - "!feeds"
    - "@feeds"
  recursion: True # Is the bot allowed to respond to its own messages?
  msglength: 16383 # Change to '4000' if you are using Mattermost <=5.x (seriously, you should upgrade!)
  logcmd: True
  logcmdparams: False

Modules:
  moduledir: "modules"
  commanddir: "commands"
  feedmap: "feedmap.json"
  window: 20
  timer: 600
  timeout: 60
  threads: 8

debug: False
